currentGame: tdu2
games:
  tdu:
    rootDirectory: "/home/foo/app/tdu"
    parsers:
      pmi: Tdu1Pmi
  tdu2:
    rootDirectory: "/home/foo/app/tdu2"
    parsers:
      bnk: Tdu2Bnk
      cpr: Tdu2Xmb
      cpr.dec: Tdu2Xmb
      xmb: Tdu2Xmb